import { useState, useEffect } from 'react';
import { getTrackerState, saveTrackerState, type TrackerState } from '../lib/storage';
import { CheckCircle2, Circle, Bot, Upload } from 'lucide-react';

export function Tracker() {
  const [state, setState] = useState<TrackerState>(getTrackerState());

  useEffect(() => {
    saveTrackerState(state);
  }, [state]);

  const toggle = (key: keyof TrackerState) => {
    setState(prev => ({ ...prev, [key]: !prev[key] }));
  };

  const tasks = [
    {
      id: 'folderCreated',
      title: 'Created bob_sessions folder',
      desc: 'Create a directory named bob_sessions in the root of your project.'
    },
    {
      id: 'filesExported',
      title: 'Exported Bob task-history markdown files',
      desc: 'Save your conversation logs with Bob as markdown files in the folder.'
    },
    {
      id: 'summaryScreenshot',
      title: 'Added Bob consumption summary screenshot',
      desc: 'Include a screenshot showing how much you utilized Bob during the hackathon.'
    },
    {
      id: 'explanationAdded',
      title: 'Added written explanation of Bob usage',
      desc: 'Document in the README exactly how Bob helped you build the project faster.'
    },
    {
      id: 'linksAdded',
      title: 'Linked generated assets to the final repo',
      desc: 'Ensure tests, docs, and code snippets generated by Bob are present in the final codebase.'
    }
  ];

  const progress = Math.round((Object.values(state).filter(Boolean).length / tasks.length) * 100);

  return (
    <div className="max-w-4xl mx-auto">
      <div className="mb-8">
        <h1 className="text-3xl font-bold text-gray-900 mb-2 flex items-center gap-3">
          <Bot className="w-8 h-8 text-blue-600" />
          IBM Bob Evidence Tracker
        </h1>
        <p className="text-gray-600">Track the required steps to prove your usage of IBM Bob for the hackathon submission. These files should be included in your final repository.</p>
      </div>

      <div className="bg-white rounded-xl shadow-sm border border-gray-200 overflow-hidden mb-8">
        <div className="p-6 border-b border-gray-100 bg-gray-50 flex items-center justify-between">
          <div>
            <h2 className="text-lg font-semibold text-gray-900">Hackathon Checklist</h2>
            <p className="text-sm text-gray-500">Required for a valid submission</p>
          </div>
          <div className="flex items-center gap-4">
            <div className="text-right">
              <span className="text-2xl font-bold text-blue-600">{progress}%</span>
              <span className="text-sm text-gray-500 block">Complete</span>
            </div>
            <div className="w-16 h-16 rounded-full border-4 border-gray-100 relative flex items-center justify-center">
              <svg className="w-full h-full transform -rotate-90 absolute" viewBox="0 0 36 36">
                <path
                  className="text-blue-600"
                  strokeDasharray={`${progress}, 100`}
                  d="M18 2.0845
                    a 15.9155 15.9155 0 0 1 0 31.831
                    a 15.9155 15.9155 0 0 1 0 -31.831"
                  fill="none"
                  stroke="currentColor"
                  strokeWidth="4"
                />
              </svg>
            </div>
          </div>
        </div>
        
        <div className="divide-y divide-gray-100">
          {tasks.map((task) => (
            <div 
              key={task.id} 
              className={`p-6 flex items-start gap-4 transition-colors hover:bg-gray-50 cursor-pointer ${
                state[task.id as keyof TrackerState] ? 'bg-blue-50/30' : ''
              }`}
              onClick={() => toggle(task.id as keyof TrackerState)}
            >
              <button className="mt-1 focus:outline-none flex-shrink-0">
                {state[task.id as keyof TrackerState] ? (
                  <CheckCircle2 className="w-6 h-6 text-green-500" />
                ) : (
                  <Circle className="w-6 h-6 text-gray-300" />
                )}
              </button>
              <div className="flex-1">
                <h3 className={`font-semibold text-lg mb-1 ${state[task.id as keyof TrackerState] ? 'text-gray-900 line-through decoration-gray-400' : 'text-gray-900'}`}>
                  {task.title}
                </h3>
                <p className="text-gray-600 text-sm mb-4">{task.desc}</p>
                
                {/* Mock Upload UI */}
                {!state[task.id as keyof TrackerState] && (
                  <div className="flex items-center gap-2 text-sm text-blue-600 bg-blue-50 px-3 py-2 rounded-md border border-blue-100 w-max" onClick={(e) => { e.stopPropagation(); toggle(task.id as keyof TrackerState); }}>
                    <Upload className="w-4 h-4" />
                    <span>Click to mark as complete</span>
                  </div>
                )}
              </div>
            </div>
          ))}
        </div>
      </div>
      
      <div className="bg-blue-50 border border-blue-200 rounded-lg p-6 flex gap-4 items-start">
        <Bot className="w-6 h-6 text-blue-600 flex-shrink-0 mt-1" />
        <div>
          <h4 className="font-semibold text-blue-900 mb-1">Remember!</h4>
          <p className="text-blue-800 text-sm">
            Do not fake Bob logs or screenshots. Use the real outputs from your IBM Bob sessions. The purpose of this checklist is to help you organize the real evidence.
          </p>
        </div>
      </div>
    </div>
  );
}
